format = """
$username\
  \
$directory\
$git_branch\
$git_status\
$fill\
$cmd_duration\
$time\
$line_break\
$character\
"""

[username]
show_always = true
format = '[$user]($style): '

[directory]
truncation_length = 4
truncation_symbol = "… /"

[directory.substitutions]
".config" = " "
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = " "

[git_status]
format = '[[($all_status $ahead_behind )](fg:#99d1db)]($style)'
ahead = ""
behind = ""
modified = ""
conflicted = ""
up_to_date = ""
diverged = "⇕"
untracked = ""
deleted = "✘"
staged = ""


[fill]
symbol = " "

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
format = '[󰥔 $time](fg:$FFFFFF)'

